# configs/phase2_local.yaml - Local testing configuration

data:
  dir: "data"                  # Local data directory
  label_file: "data/labels.csv"  # Local label file path

model:
  name: "emotion_attention_net"  # Custom model for RAF-DB with attention
  pretrained: true               # Using pretrained backbone weights

training:
  batch_size: 16                 # Smaller batch for local testing
  epochs: 1                      # Just 1 epoch for smoke test
  lr: 0.0001                     # Lower learning rate for fine-tuning
  weight_decay: 1e-5             # Weight decay for regularization
  seed: 42                       # Keep seed consistent for reproducibility
  early_stopping_patience: 15    # More patience for the complex dataset
  mixup_alpha: 0.2               # Mixup augmentation for better generalization
  label_smoothing: 0.1           # Label smoothing helps with calibration
  grad_clip_value: 1.0           # Gradient clipping to prevent exploding gradients
  k_fold: 0                      # Default to regular training (not k-fold cross-validation)
  
  lr_scheduler:
    type: "reduce_on_plateau"    # Reduce LR when validation loss plateaus
    factor: 0.5                  # Reduce by half
    patience: 5                  # Wait 5 epochs before reducing LR
    min_lr: 1e-6                 # Minimum learning rate

  optimizer:
    type: "adamw"                # AdamW optimizer for weight decay handling

# Local testing optimizations
puhti:
  num_workers: 2                 # Fewer workers for local testing
  pin_memory: true               # Use pinned memory for faster GPU transfers
  mixed_precision: true          # Use mixed precision for faster computation
  checkpoint_freq: 1             # Save checkpoint every epoch
  grad_clip: 1.0                 # Gradient clipping value

augmentation:
  # Advanced augmentations for RAF-DB
  random_resized_crop:
    scale: [0.8, 1.0]
    size: 224
  random_horizontal_flip: true
  random_affine:
    degrees: 10
    translate: [0.1, 0.1]
  color_jitter:
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2

# RAF-DB has 7 emotion classes in this order:
classes:
  - 'anger'
  - 'fear'
  - 'happy'
  - 'sad'
  - 'surprise'
  - 'neutral'
  - 'disgust'

paths:
  log_dir: "outputs/logs/phase2/${model.name}"
  output_dir: "models/phase2/${model.name}"
  metrics_dir: "outputs/metrics/phase2/${model.name}"
  checkpoints_dir: "outputs/checkpoints/phase2/${model.name}" 