# configs/phase1.yaml

data:
  dir: "data/fer2013_dataset/processed"

model:
  name: "efficientnet_b0"        # Best performing model for emotion recognition
  pretrained: true               # Using pretrained weights is recommended for FER2013

training:
  batch_size: 64                 # Increased from 32 for better gradient estimates
  epochs: 50                     # Increased from 30 for better convergence
  lr: 0.0005                     # Reduced from 0.001 for more stable training
  weight_decay: 2e-5             # Better regularization for FER2013
  seed: 42                       # Keep seed consistent for reproducibility
  early_stopping_patience: 10    # Stop if no improvement for 10 epochs
  lr_scheduler:
    type: "cosine"               # Cosine annealing scheduler works well
    T_max: 50                    # Match with number of epochs
    eta_min: 1e-6                # Minimum learning rate
  optimizer:
    type: "adamw"                # AdamW instead of Adam for weight decay handling

augmentation:
  cutout_prob: 0.5               # Helps with overfitting
  mixup_alpha: 0.2               # Mild mixup for data augmentation

paths:
  log_dir: "outputs/logs/${model.name}"
  output_dir: "models/${model.name}"
  metrics_dir: "outputs/metrics/${model.name}"
  checkpoints_dir: "outputs/checkpoints/${model.name}"